Progetto_gestione_permessi/src/main/java/it/progetto/controllers/ListaPermessiController.java
package it.progetto.controllers;

import java.util.ArrayList;


import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import it.progetto.domain.Permesso;


import it.progetto.service.RichiestaService;

@ManagedBean
@ViewScoped
public class ListaPermessiController {
	
	private ArrayList<Permesso> ListaPermessi;
	private ArrayList<Permesso> ListaPermessiUtente;
	private ArrayList<Permesso> ListaPermessiConcessi;
	private ArrayList<Permesso> ListaFerieUtente;
	private ArrayList<Permesso> ListaFerieConcesse;
	private ArrayList<Permesso> ListaRichieste;
	
	@ManagedProperty(value = "#{richiestaService}")
    private RichiestaService richiestaService;
	

	
	public ArrayList<Permesso> getlistaPermessi(){		
		if (this.ListaPermessi == null) {
            this.ListaPermessi = richiestaService.listaPermessi();
        }
        return ListaPermessi;	
	}
	
	public ArrayList<Permesso> getListaPermessiUtente(){		
		if (this.ListaPermessiUtente == null) {
            this.ListaPermessiUtente = richiestaService.listaPermessiUtente();
        }
        return ListaPermessiUtente;	
	}
	public ArrayList<Permesso> getlistaPermessiConcessi(){		
		if (this.ListaPermessiConcessi == null) {
            this.ListaPermessiConcessi = richiestaService.listaPermessiConcessi();
        }
        return ListaPermessiConcessi;	
	}

	public ArrayList<Permesso> getlistaFerieUtente(){		
		if (this.ListaFerieUtente == null) {
            this.ListaFerieUtente = richiestaService.listaFerieUtente();
        }
        return ListaFerieUtente;	
	}


	public ArrayList<Permesso> getlistaFerieConcesse(){		
		if (this.ListaFerieConcesse == null) {
            this.ListaFerieConcesse = richiestaService.listaFerieConcesse();
        }
        return ListaFerieConcesse;	
	}
	
	public ArrayList<Permesso> getListaRichieste(){
		if (this.ListaRichieste == null) {
            this.ListaRichieste = richiestaService.richiesteRicevute();
        }
        return ListaRichieste;	
	}
	
	public RichiestaService getRichiestaService() {
		return richiestaService;
	}



	public void setRichiestaService(RichiestaService richiestaService) {
		this.richiestaService = richiestaService;
	}
	
}

Progetto_gestione_permessi/src/main/java/it/progetto/controllers/LoginController.java
package it.progetto.controllers;



import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;


import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.core.Authentication;

import org.springframework.security.core.context.SecurityContextHolder;

import it.progetto.service.RichiestaService;

@ManagedBean(name="loginController")
@RequestScoped
public class LoginController {
	
	
    private String username = null;
    private String password = null;
    public String num_richieste = null;
    
    @ManagedProperty(value="#{authenticationManager}")
    private AuthenticationManager authenticationManager = null;
    
    @ManagedProperty(value="#{richiestaService}")
    private RichiestaService richiestaService;
  
	
    private Long idConnesso;
    
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}
	
	public void setPassword(String password) {
		this.password = password;
	}
	
	public AuthenticationManager getAuthenticationManager() {
		return authenticationManager;
	}
	
	public void setAuthenticationManager(AuthenticationManager authenticationManager) {
		this.authenticationManager = authenticationManager;
	}
	
	
	public String getUtenteConnesso() {
		Authentication autenticato = SecurityContextHolder.getContext().getAuthentication();
	    String name = autenticato.getName();
	
		return name;
	}
	
	public String getNum_richieste() {
		if (this.num_richieste == null) {
			this.num_richieste = richiestaService.richieste();	
		}
		return num_richieste;
	}
	
	public String AreaResp() {
		if(richiestaService.isResponsabile()) {
			return "/secure/area_responsabili.xhtml?faces-redirect=true";
		}
		return "layoutPrivato.xhtml?faces-redirect=true&resp=1";
	}

	public RichiestaService getRichiestaService() {
		return richiestaService;
	}

	public void setRichiestaService(RichiestaService richiestaService) {
		this.richiestaService = richiestaService;
	}
	
	

	
	
	
	
}

Progetto_gestione_permessi/src/main/webapp/secure/area_responsabili.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" 
	xmlns:b="http://bootsfaces.net/ui">
	
	<h:head>
		<title>Gestionale permessi</title>
		
		<h:outputStylesheet library="css" name="style.css" />
	</h:head>

	<h:body style="padding-top: 50px; padding-bottom: 20px;">
		<b:navBar brand="Gestionale Permessi" fixed="top" brandHref="/template/layoutPrivato.xhtml">
			<b:navbarLinks>
				<b:dropMenu value="Report Permessi giornalieri">
					<b:navLink value="Tutti i permessi" href="/secure/permessi_all.xhtml"></b:navLink>
					<b:navLink value="permessi concessi" href="/secure/permessi_concessi.xhtml"></b:navLink>
				</b:dropMenu>
				<b:dropMenu value="Report richiesta ferie">
					<b:navLink value="Tutte le richieste" href="/secure/ferie_all.xhtml"></b:navLink>
					<b:navLink value="ferie concesse" href="/secure/ferie_concesse.xhtml"></b:navLink>
				</b:dropMenu> 
			</b:navbarLinks>
			<b:navbarLinks pull="right">
				<b:navLink value="#{loginController.utenteConnesso}"></b:navLink>
			
			</b:navbarLinks>
	</b:navBar> 
	
	 <ui:fragment rendered="${!empty param['concesso']}">
				 	<b:alert><div class="alert  alert-danger"  style="text-align: center">
				 		<font color="green"> HAI APPROVATO LA RICHIESTA, UNA E-MAIL E' STATA INVIATA ALL' UTENTE </font>
				 	</div></b:alert>
            	</ui:fragment>
     <ui:fragment rendered="${!empty param['negato']}">
				 	<b:alert><div class="alert  alert-danger"  style="text-align: center">
				 		<font color="red"> HAI NEGATO LA RICHIESTA, UNA E-MAIL E' STATA INVIATA ALL' UTENTE </font>
				 	</div></b:alert>
            	</ui:fragment>
	
		
				 <div class="richieste" style="width:90%;float:center; margin:0px auto ">
			<h2 >Area Responsabili</h2>
			<h:form>
			<p:commandButton update=":form:utentiDetail"  oncomplete="PF('utentiDialog').show()" value="LISTA UTENTI" class="btn btn-primary btn-lg" style="padding:7px; margin:5px; "></p:commandButton>
			</h:form>
			<hr  /><h:form id="form">
				 		<p:dataTable value="#{listaPermessiController.listaRichieste}" var="permesso" id="lista"  >
				 			<p:column style="width:7%">
								<f:facet name="header">
									<h:outputText value="UTENTE" />
								</f:facet>
							<h:outputText value="#{permesso.utente}" />
							</p:column>	
							<p:column>
								<f:facet name="header">
									<h:outputText value="MOTIVO" />
								</f:facet>
							<h:outputText value="#{permesso.motivo}" />
							</p:column>	
							
							<p:column>
								<f:facet name="header">
									<h:outputText value="DATA" />
								</f:facet>
									<h:outputText value="#{permesso.data_permesso}" /><br/>
									<h:outputText value="dalle ore: #{permesso.ora_inizio} - alle ore: #{permesso.ora_rientro}"/>
							</p:column>	
							<p:column>
								<f:facet name="header">
									<h:outputText value="GIORNO INIZIO" />
								</f:facet>
									<h:outputText value="#{permesso.giorno_inizio}" /><br/>					
							</p:column>
							<p:column>
								<f:facet name="header">
									<h:outputText value="GIORNO RIENTRO" />
								</f:facet>
									<h:outputText value="#{permesso.giorno_fine}" /><br/>					
							</p:column>	 	
							<p:column>
					
								<p:commandButton update=":form:permessoDetail" value="CONCEDI"  oncomplete="PF('permessoDialog').show()" class="btn btn-primary btn-lg" style="padding:7px; margin:5px">
									<f:setPropertyActionListener value="#{permesso}" target="#{selezioneController.permessoSelected}" ></f:setPropertyActionListener>
								</p:commandButton>
								<p:commandButton update=":form:negaDetail" value="NEGA"  oncomplete="PF('negaDialog').show()" class="btn btn-primary btn-lg" style="padding:7px; margin:5px">
									<f:setPropertyActionListener value="#{permesso}" target="#{selezioneController.permessoSelected}" ></f:setPropertyActionListener>
								</p:commandButton>
							</p:column>					 		
				 		</p:dataTable>
				 		<hr/>
		<!-- DIALOG CONCEDI PERMESSO -->
		<p:dialog widgetVar="permessoDialog" width="300" height="400" modal="true" resizable="false">
			<p:outputPanel id="permessoDetail">
				<h3><b>Concessione Permesso</b></h3><hr/>
				<font color="green"><b>Stai per accordare la richiesta di permesso, controlla i dati prima di procedere</b><br/></font>
				
			
				<p:panelGrid columns="2" rendered="#{not empty selezioneController.permessoSelected}" >
				
				  <h:outputText  value="id_permesso" />
				<h:outputText  value="#{selezioneController.permessoSelected.idpermesso}"/>
				
				<h:outputText  value="ID utente" />
				<h:outputText  value="#{selezioneController.permessoSelected.utente}"/>
				
				<h:outputText  value="motivo" />
				<h:outputText  value="#{selezioneController.permessoSelected.motivo}"/>
				
				<h:outputText  value="data" />
				<h:outputText  value="#{selezioneController.permessoSelected.data_permesso}"/>
				
				<h:outputText  value="giorno inizio" />
				<h:outputText  value="#{selezioneController.permessoSelected.giorno_inizio}"/>
				
				<h:outputText  value="giorno fine" />
				<h:outputText  value="#{selezioneController.permessoSelected.giorno_fine}"/>

				</p:panelGrid>
				<hr/>
					<h:commandButton class="btn btn-primary btn-lg" onclick="concedi.close();" value="CONCEDI" action="#{selezioneController.concediPermesso}" style="padding:7px; margin:5px"> </h:commandButton>
					<h:commandButton class="btn btn-primary btn-lg" onclick="concedi.close();" value="ANNULLA" style="padding:7px; margin:5px"> </h:commandButton>
			</p:outputPanel>
			</p:dialog>
	
								
		<!-- DIALOG NEGA PERMESSO -->		
		<p:dialog widgetVar="negaDialog" width="300" height="400" modal="true" resizable="false">
		<p:outputPanel id="negaDetail">
			<h3><b>Nega Permesso</b></h3><hr/>
			<font color="red"><b>Stai per negare la richiesta di permesso, controlla i dati prima di procedere</b><br/></font>

			<p:panelGrid columns="2" rendered="#{not empty selezioneController.permessoSelected}" >
			
			<h:outputText  value="id_utente" />
			<h:outputText  value="#{selezioneController.permessoSelected.utente}"/>
			
			<h:outputText  value="motivo" />
			<h:outputText  value="#{selezioneController.permessoSelected.motivo}"/>
			
			<h:outputText  value="data" />
			<h:outputText  value="#{selezioneController.permessoSelected.data_permesso}"/>
			
			<h:outputText  value="giorno inizio" />
			<h:outputText  value="#{selezioneController.permessoSelected.giorno_inizio}"/>
			
			<h:outputText  value="giorno fine" />
			<h:outputText  value="#{selezioneController.permessoSelected.giorno_fine}"/>

			</p:panelGrid>
			<hr/>
				<h:commandButton class="btn btn-primary btn-lg" onclick="concedi.close();" value="NEGA" action="#{selezioneController.negaPermesso}" style="padding:7px; margin:5px"> </h:commandButton>
				<h:commandButton class="btn btn-primary btn-lg" onclick="concedi.close();" value="ANNULLA" style="padding:7px; margin:5px"> </h:commandButton>
		</p:outputPanel>
		</p:dialog>
								
										
	<!-- DIALOG LISTA UTENTI -->
	<p:dialog widgetVar="utentiDialog"  modal="true" resizable="false">
			<p:dataList id="utentiDetail" value="#{selezioneController.listaUtenti}" var="utente" >
				<f:facet name="header">
    									LISTA UTENTI
    									
 								    </f:facet><hr/>
 								  <b> #{utente.nome} #{utente.cognome}  (</b>ID: <b>#{utente.idutente}</b>) --- #{utente.email} <br/><hr/>
			</p:dataList>							
			<hr/>
				<h:commandButton class="btn btn-primary btn-lg" onclick="concedi.close();" value="CHIUDI" style="padding:7px; margin:5px"> </h:commandButton>
			
	</p:dialog>
	</h:form>
</div>
            	
</h:body>
</html>

Progetto_gestione_permessi/src/main/webapp/secure/ferie_all.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" 
	xmlns:b="http://bootsfaces.net/ui">

	<h:head>
		<title>Gestionale permessi</title>
		
		<h:outputStylesheet library="css" name="style.css" />
	</h:head>

	<h:body style="padding-top: 50px; padding-bottom: 20px;">

		<b:navBar brand="Gestionale Permessi" fixed="top" brandHref="/template/layoutPrivato.xhtml">
			<b:navbarLinks>
				
				<b:dropMenu value="Report Permessi">
					<b:navLink value="Tutti i permessi" href="/secure/permessi_all.xhtml"></b:navLink>
					<b:navLink value="permessi concessi" href="/secure/permessi_concessi.xhtml"></b:navLink>
				</b:dropMenu>
				<b:dropMenu value="Report richiesta ferie">
					<b:navLink value="Tutte le richieste" href="/secure/ferie_all.xhtml"></b:navLink>
					<b:navLink value="ferie concesse" href="/secure/ferie_concesse.xhtml"></b:navLink>
				</b:dropMenu>
			</b:navbarLinks>
	
			
			<b:navbarLinks pull="right">
				<b:navLink value="#{loginController.utenteConnesso}"></b:navLink>
			</b:navbarLinks>
		</b:navBar>
	
	
	<b:container>
			<h2>Lista Ferie richieste dall' utente :
			<h:outputText value="#{loginController.utenteConnesso}" ></h:outputText></h2>
			<br/><hr/>
			<b:dataTable value="#{listaPermessiController.listaFerieUtente}" var="permesso" id="lista"
				styleClass="table table-striped table-bordered" style="width:100%">
				<h:column>
				<f:facet name="header">
						<h:outputText value="ID PERMESSO" />
					</f:facet>
					<h:outputText value="#{permesso.idpermesso}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="motivazione" />
					</f:facet>
					<h:outputText value="#{permesso.motivo}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="RESPONSABILE" />
					</f:facet>
					<h:outputText value="#{permesso.responsabile}" />
				</h:column>
				<h:column>
				<f:facet name="header">
						<h:outputText value="GIORNO INIZIO" />
					</f:facet>
					<h:outputText value="#{permesso.giorno_inizio}" /><br/>					
				</h:column>
				<h:column>
				<f:facet name="header">
						<h:outputText value="GIORNO RIENTRO" />
					</f:facet>
					<h:outputText value="#{permesso.giorno_fine}" /><br/>					
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="STATO" />
					</f:facet>
					concesso: <b><font size="5px" ><h:outputText value=" #{permesso.concesso}" /></font></b>
					
				</h:column>
			</b:dataTable>
		</b:container>
				
	</h:body>
</html>

Progetto_gestione_permessi/src/main/webapp/secure/ferie_concesse.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui">

	<h:head>
		<title>Gestionale permessi</title>
		
		<h:outputStylesheet library="css" name="style.css" />
	</h:head>

	<h:body style="padding-top: 50px; padding-bottom: 20px;">

		<b:navBar brand="Gestionale Permessi" fixed="top" brandHref="/template/layoutPrivato.xhtml">
			<b:navbarLinks>
				
				<b:dropMenu value="Report Permessi">
					<b:navLink value="Tutti i permessi" href="/secure/permessi_all.xhtml"></b:navLink>
					<b:navLink value="permessi concessi" href="/secure/permessi_concessi.xhtml"></b:navLink>
				</b:dropMenu>
				<b:dropMenu value="Report richiesta ferie">
					<b:navLink value="Tutte le richieste" href="/secure/ferie_all.xhtml"></b:navLink>
					<b:navLink value="ferie concesse" href="/secure/ferie_concesse.xhtml"></b:navLink>
				</b:dropMenu>
			</b:navbarLinks>
	
			
			<b:navbarLinks pull="right">
				<b:navLink value="#{loginController.utenteConnesso}"></b:navLink>
			</b:navbarLinks>
		</b:navBar>
		
		
		
	<b:container>
			<h2>Lista Ferie concesse all' utente :
			<h:outputText value="#{loginController.utenteConnesso}" ></h:outputText></h2>
			<br/><hr/>
			<b:dataTable value="#{listaPermessiController.listaFerieConcesse}" var="permesso" id="lista"
				styleClass="table table-striped table-bordered" style="width:100%">
				<h:column>
				<f:facet name="header">
						<h:outputText value="id_permesso" />
					</f:facet>
					<h:outputText value="#{permesso.idpermesso}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="motivazione" />
					</f:facet>
					<h:outputText value="#{permesso.motivo}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="responsabile" />
					</f:facet>
					<h:outputText value="#{permesso.responsabile}" />
				</h:column>
				<h:column>
				<f:facet name="header">
						<h:outputText value="giorno inizio" />
					</f:facet>
					<h:outputText value="#{permesso.giorno_inizio}" /><br/>					
				</h:column>
				<h:column>
				<f:facet name="header">
						<h:outputText value="giorno rientro" />
					</f:facet>
					<h:outputText value="#{permesso.giorno_fine}" /><br/>					
				</h:column>
				
			</b:dataTable>
		</b:container>
			
			
		
	
	</h:body>
</html>

Progetto_gestione_permessi/src/main/webapp/secure/permessi_all.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui">

	<h:head>
		<title>Gestionale permessi</title>
		
		<h:outputStylesheet library="css" name="style.css" />
	</h:head>

	<h:body style="padding-top: 50px; padding-bottom: 20px;">

		<b:navBar brand="Gestionale Permessi" fixed="top" brandHref="/template/layoutPrivato.xhtml">
			<b:navbarLinks>
				
				<b:dropMenu value="Report Permessi">
					<b:navLink value="Tutti i permessi" href="/secure/permessi_all.xhtml"></b:navLink>
					<b:navLink value="permessi concessi" href="/secure/permessi_concessi.xhtml"></b:navLink>
				</b:dropMenu>
				<b:dropMenu value="Report richiesta ferie">
					<b:navLink value="Tutte le richieste" href="/secure/ferie_all.xhtml"></b:navLink>
					<b:navLink value="ferie concesse" href="/secure/ferie_concesse.xhtml"></b:navLink>
				</b:dropMenu>
			</b:navbarLinks>
	
			
			<b:navbarLinks pull="right">
				<b:navLink value="#{loginController.utenteConnesso}"></b:navLink>
			</b:navbarLinks>
		</b:navBar>
		
		
		
	<b:container>
			<h2>Richieste di Permesso effettuate dall' utente :
			<h:outputText value="#{loginController.utenteConnesso}" ></h:outputText></h2>
			<br/><hr/>
			<div class="table">
			<b:dataTable value="#{listaPermessiController.listaPermessiUtente}" var="permesso" id="lista" >
				<h:column>
				<f:facet name="header">
						<h:outputText value="ID RICHIESTA" />
					</f:facet>
					<h:outputText value="#{permesso.idpermesso}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="MOTIVO" />
					</f:facet>
					<h:outputText value="#{permesso.motivo}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="RESPONSABILE" />
					</f:facet>
					<h:outputText value="#{permesso.responsabile}" />
				</h:column>
				<h:column>
				<f:facet name="header">
						<h:outputText value="DATA" />
					</f:facet>
					<h:outputText value="#{permesso.data_permesso}" /><br/>
					<h:outputText value="dalle ore: #{permesso.ora_inizio} - alle ore:  #{permesso.ora_rientro}"/>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="STATO" />
					</f:facet>
					concesso: <b><font size="5px" ><h:outputText value=" #{permesso.concesso}" /></font></b>
					
				</h:column>
				
			</b:dataTable>
			</div>
		</b:container>
			
			
		
	
	</h:body>
</html>

Progetto_gestione_permessi/src/main/webapp/secure/permessi_concessi.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui">

	<h:head>
		<title>Gestionale permessi</title>
		
		<h:outputStylesheet library="css" name="style.css" />
	</h:head>

	<h:body style="padding-top: 50px; padding-bottom: 20px;">

		<b:navBar brand="Gestionale Permessi" fixed="top" brandHref="/template/layoutPrivato.xhtml">
			<b:navbarLinks>
				
				<b:dropMenu value="Report Permessi">
					<b:navLink value="Tutti i permessi" href="/secure/permessi_all.xhtml"></b:navLink>
					<b:navLink value="permessi concessi" href="/secure/permessi_concessi.xhtml"></b:navLink>
				</b:dropMenu>
				<b:dropMenu value="Report richiesta ferie">
					<b:navLink value="Tutte le richieste" href="/secure/ferie_all.xhtml"></b:navLink>
					<b:navLink value="ferie concesse" href="/secure/ferie_concesse.xhtml"></b:navLink>
				</b:dropMenu>
			</b:navbarLinks>
	
			
			<b:navbarLinks pull="right">
				<b:navLink value="#{loginController.utenteConnesso}"></b:navLink>
			</b:navbarLinks>
		</b:navBar>
		
		
		
	<b:container>
			<h2>Lista Permessi Concessi per l' utente :
			<h:outputText value="#{loginController.utenteConnesso}" ></h:outputText></h2>
			<br/><hr/>
			<b:dataTable value="#{listaPermessiController.listaPermessiConcessi}" var="permesso" id="lista"
				styleClass="table table-striped table-bordered" style="width:100%">
				<h:column>
				<f:facet name="header">
						<h:outputText value="id_permesso" />
					</f:facet>
					<h:outputText value="#{permesso.idpermesso}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="motivo" />
					</f:facet>
					<h:outputText value="#{permesso.motivo}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="responsabile" />
					</f:facet>
					<h:outputText value="#{permesso.responsabile}" />
				</h:column>
				<h:column>
				<f:facet name="header">
						<h:outputText value="data" />
					</f:facet>
					<h:outputText value="#{permesso.data_permesso}" /><br/>
					<h:outputText value="dalle ore: #{permesso.ora_inizio} - alle ore: #{permesso.ora_rientro}"/>
				</h:column>
				
				
			</b:dataTable>
		</b:container>
			
			
		
	
	</h:body>
</html>